### ISSUE TITLE
Uncaught ReferenceError when calling MapView#getVenueWithAlias

### ISSUE THREAD

**Issue by jcyu0208** [Mapwize/mapwize-android-sdk#3]
Hello,

I'm using the sample application provided and tried to make a request to get a venue with alias using this in onCreate of MainActivity

``` java
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ....

        Exception exception = new Exception();
        mapview = (MWZMapView) this.findViewById(R.id.mwzview);
        mapview.setListener(this);

        mapview.getVenueWithAlias("test_alias", new VenueCallbackInterface() {1
            @Override
            public void onResponse(MWZVenue venue) {

            }
        });
    }
```

In the xml file, I've set the appropriate API Key provided in the dashboard.

However, I keep getting this error: 

```
06-17 14:13:52.500 11670-11670/io.mapwize.example D/onJsConsoleCallback: Javascript console message - ERROR : Uncaught ReferenceError: Mapwize is not defined
06-17 14:13:52.501 11670-11670/io.mapwize.example I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: Mapwize is not defined", source:  (1)
```

May I ask if there's any additional setup needed?

Edit: The version I'm using is 1.5.0

**Comment by mathieugerard** [comment]
This issue comes from the fact that the MWZMapView is not fully loaded at the moment getVenueWithAlias is called, and this causes issues.
To solve this problem, the listener callback onMapLoaded has been added in the 1.6.0 version of the SDK. All map methods can be safely called after that callback has been triggered.
Hope this helps

**Comment by jcyu0208** [comment]
Hi @mathieugerard sounds great! I was going to ask for a callback. Let me get 1.6.0 in my project and try it again. 

Thanks for the quick response.
