### ISSUE TITLE
Warning: unknown enum constant Include.NON_NULL

### ISSUE THREAD

**Issue by chi2222** [Mapwize/mapwize-android-sdk#6]
When I try to run the application, this warning appears and it is not possible to install the application.

**Comment by mathieugerard** [comment]
Hi. Sorry for the late reaction.
This SDK is deprecated. If you are using it in production with a paid Mapwize plan, please email support@mapwize.io. Otherwise, please refer to docs.mapwize.io to get the latest SDK.
Regards.
Mathieu
